sudo: required

language: julia

os:
    - linux

julia:
    - nightly
    - 0.7.0

matrix:
    - PYTHON=Conda-python

addons:
    apt:
        packages:
            - gfortran

install:
    - source .ci/travis.sh
    - if [ "$TRAVIS_JULIA_VERSION" = "0.7.0" ]; then sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended; fi
    - julia .ci/install.jl

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
    - julia test/runtests.jl
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-docs.sh; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-paper.sh; fi

cache:
    directories:
        - $HOME/.cache/Tectonic
        - $HOME/miniconda
        - /tmp/texlive
        - $HOME/.texlive

after_failure:
    - sleep 3
